FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml .
RUN pip install uv && uv sync

COPY ./application/backend /app/application/backend
COPY --from=builder /app/application/frontend /app/application/frontend

WORKDIR /app/application/backend

EXPOSE 5000
CMD ["uv", "run", "gunicorn", "-b", "0.0.0.0:5000", "wsgi:application"]